version: '2'

services:

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command:
        python manage.py runserver 0.0.0.0:8000

  redis:
    image: daocloud.io/redis
