version: '2'

services:

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    environment:
      - REDIS_CONN=redis://redis:6379/2
    depends_on:
      - redis
    command:
        python manage.py runserver 0.0.0.0:8000

  redis:
    image: daocloud.io/redis
